const cardData = [
  {
    id: 1,
    title: "Sunset Beach",
    description: "A peaceful beach with a golden sunset.",
    imageUrl: "https://picsum.photos/300/200?random=1",
  },
  {
    id: 2,
    title: "Mountain Peaks",
    description: "Snow-capped mountains touching the sky.",
    imageUrl: "https://picsum.photos/300/200?random=2",
  },
  {
    id: 3,
    title: "City Lights",
    description: "The city shines bright at night.",
    imageUrl: "https://picsum.photos/300/200?random=3",
  },
  {
    id: 4,
    title: "Autumn Forest",
    description: "Golden leaves covering the forest ground.",
    imageUrl: "https://picsum.photos/300/200?random=4",
  },
  {
    id: 5,
    title: "Desert Dunes",
    description: "Smooth dunes under a clear sky.",
    imageUrl: "https://picsum.photos/300/200?random=5",
  },
  {
    id: 6,
    title: "Serene Lake",
    description: "A tranquil lake reflecting the sky.",
    imageUrl: "https://picsum.photos/300/200?random=6",
  },
  {
    id: 7,
    title: "Bustling Market",
    description: "Vibrant stalls filled with fresh produce.",
    imageUrl: "https://picsum.photos/300/200?random=7",
  },
  {
    id: 8,
    title: "Historic Castle",
    description: "An ancient castle standing tall.",
    imageUrl: "https://picsum.photos/300/200?random=8",
  },
  {
    id: 9,
    title: "Snowy Village",
    description: "A quiet village covered in snow.",
    imageUrl: "https://picsum.photos/300/200?random=9",
  },
  {
    id: 10,
    title: "Lush Greenery",
    description: "A dense jungle full of life.",
    imageUrl: "https://picsum.photos/300/200?random=10",
  },
  {
    id: 11,
    title: "Misty Mountains",
    description: "Fog rolling over the peaks.",
    imageUrl: "https://picsum.photos/300/200?random=11",
  },
  {
    id: 12,
    title: "Golden Fields",
    description: "Wheat fields swaying in the breeze.",
    imageUrl: "https://picsum.photos/300/200?random=12",
  },
  {
    id: 13,
    title: "Cosmic Wonders",
    description: "A mesmerizing view of the galaxy.",
    imageUrl: "https://picsum.photos/300/200?random=13",
  },
  {
    id: 14,
    title: "Rainy Streets",
    description: "Puddles forming in a busy street.",
    imageUrl: "https://picsum.photos/300/200?random=14",
  },
  {
    id: 15,
    title: "Flower Garden",
    description: "A colorful garden in full bloom.",
    imageUrl: "https://picsum.photos/300/200?random=15",
  },
  {
    id: 16,
    title: "Wooden Cabin",
    description: "A cozy cabin in the woods.",
    imageUrl: "https://picsum.photos/300/200?random=16",
  },
  {
    id: 17,
    title: "Vibrant Festival",
    description: "A lively celebration with fireworks.",
    imageUrl: "https://picsum.photos/300/200?random=17",
  },
  {
    id: 18,
    title: "Starry Night",
    description: "A breathtaking view of the night sky.",
    imageUrl: "https://picsum.photos/300/200?random=18",
  },
  {
    id: 19,
    title: "Ancient Ruins",
    description: "Remnants of a lost civilization.",
    imageUrl: "https://picsum.photos/300/200?random=19",
  },
  {
    id: 20,
    title: "Urban Jungle",
    description: "Skyscrapers towering over the streets.",
    imageUrl: "https://picsum.photos/300/200?random=20",
  },
  {
    id: 21,
    title: "Frozen Lake",
    description: "A lake frozen solid in winter.",
    imageUrl: "https://picsum.photos/300/200?random=21",
  },
  {
    id: 22,
    title: "Rolling Hills",
    description: "Green hills stretching for miles.",
    imageUrl: "https://picsum.photos/300/200?random=22",
  },
  {
    id: 23,
    title: "Sunny Coastline",
    description: "Waves crashing on the shore.",
    imageUrl: "https://picsum.photos/300/200?random=23",
  },
  {
    id: 24,
    title: "Hiking Trail",
    description: "A scenic path through the mountains.",
    imageUrl: "https://picsum.photos/300/200?random=24",
  },
  {
    id: 25,
    title: "Lighthouse View",
    description: "A lonely lighthouse standing tall.",
    imageUrl: "https://picsum.photos/300/200?random=25",
  },
  {
    id: 26,
    title: "Cherry Blossoms",
    description: "Pink petals covering the ground.",
    imageUrl: "https://picsum.photos/300/200?random=26",
  },
  {
    id: 27,
    title: "Wildlife Safari",
    description: "Lions and zebras in their natural habitat.",
    imageUrl: "https://picsum.photos/300/200?random=27",
  },
  {
    id: 28,
    title: "Boating Adventure",
    description: "A boat floating on a peaceful river.",
    imageUrl: "https://picsum.photos/300/200?random=28",
  },
  {
    id: 29,
    title: "Deep Forest",
    description: "Tall trees forming a canopy.",
    imageUrl: "https://picsum.photos/300/200?random=29",
  },
  {
    id: 30,
    title: "Mysterious Cave",
    description: "A dark cave waiting to be explored.",
    imageUrl: "https://picsum.photos/300/200?random=30",
  },
];

export default cardData;
